name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
  workflow_dispatch:

jobs:
  black:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: pip3 install -r requirements_test.txt
      - name: "Black codestyle check"
        run: black --check --diff .
